name: Ruby Sort Example

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        ruby-version: [1.9.3, 2.0.0, 2.7, 3.0, 3.3]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Run script
        run: |
          ruby -v
          ruby scripts/workflows/ruby-example/sort.rb
